module.exports.descriptors = [
  "da Floresta",
  "Antigo",
  "das Pedras",
  "do Rugido",
  "do Corrego",
  "da Cachoeira",
  "do Silencio",
  "do Pau",
  "do Sapo",
  "Selvagem",
  "Mistico",
  "do Veado",
  "do Urso",
  "do Oceano",
  "do Mar",
  "do Ceu",
  "da Poeira",
  "do Diamante",
];

module.exports.places = [
  "Camping do Planalto",
  "Camping do Vilarejo",
  "Camping do Canion",
  "Camping da Lagoa",
  "Camping da Turma",
  "Camping do Cavalo",
  "Camping da Cidade Fantasma",
  "Camping",
  "Camping Esquecido",
  "Camping do Sertao",
  "Camping do Rio",
  "Camping do Corrego",
  "Camping da Represa",
  "Camping da Baia",
  "Camping da Primavera",
  "Camping da Costa",
  "Camping das Dunas",
  "Camping da Mula",
  "Camping do Caçador",
  "Camping da Serra",
  "Camping do Pau Oco",
];
